name: backend
description: "Backend for the app"
environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  http: ^1.3.0
  # Server-side dependencies
  shelf: ^1.4.0
  shelf_router: ^1.0.0
  flutter_gemini: ^3.0.0
  mongo_dart: ^0.9.4

dev_dependencies:
  # Recommended lints for Dart projects
  lints: ^5.1.1
  test: ^1.21.0
  